# Generated by Django 4.2.14 on 2025-07-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_lifting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='ipf_points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
