# Generated by Django 4.2.16 on 2024-09-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_lifting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='heigth',
            field=models.FloatField(default=70),
            preserve_default=False,
        ),
    ]
