# Generated by Django 4.2.16 on 2024-09-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_lifting', '0002_competitor_heigth'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
