# Generated by Django 4.2.14 on 2025-07-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_lifting', '0002_competitor_ipf_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='ipf_points',
            field=models.FloatField(default=0.0),
        ),
    ]
