# Generated by Django 4.2.14 on 2025-07-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_lifting', '0003_alter_competitor_ipf_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=8),
        ),
    ]
