# Generated by Django 4.2.16 on 2024-11-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_lifting', '0004_alter_competitor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lift',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
