# Generated by Django 4.2.14 on 2025-07-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_lifting', '0004_competition_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='gender',
        ),
        migrations.AddField(
            model_name='competitor',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=8),
        ),
    ]
