# Generated by Django 4.2.16 on 2024-11-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_lifting', '0005_lift_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
