# Generated by Django 4.2.16 on 2024-11-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_lifting', '0006_alter_lift_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='valid',
            field=models.CharField(choices=[('valid', 'Válido'), ('invalid', 'No Válido'), ('not_performed', 'No Realizado')], default='not_performed', max_length=15),
        ),
    ]
